allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  '@node-rs/bcrypt': true
  bcrypt: true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

overrides:
  drizzle-orm: ^0.45.2
  esbuild@^0.25.4: 0.28.2
  sharp: ^0.35.3
